//! Raw FFI bindings to libtorrent-rasterbar via the custom C shim.
//!
//! The bindings themselves are generated by `bindgen` at build time from
//! `wrapper.h` — see `build.rs` for the full pipeline.
//!
//! All symbols are unsafe by definition (C ABI, raw pointers, etc.). The
//! safe RAII wrappers live in the `libtorrent-safe` crate; downstream
//! consumers should depend on that crate, not this one, unless they need
//! to extend the FFI surface.
//!
//! Linux x86_64 only.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(clippy::missing_safety_doc)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// Smoke test the link line: if linking failed, this won't compile.
#[cfg(all(test, feature = "bundled"))]
mod link_smoke {
    use super::*;

    #[test]
    fn lt_buf_free_null_is_safe() {
        // A no-op on null per libtorrent_shim.cpp; serves to assert that
        // the symbol resolved at link time.
        unsafe { lt_buf_free(std::ptr::null_mut()) };
    }

    #[test]
    fn lt_alert_payload_free_null_is_safe() {
        unsafe { lt_alert_payload_free(std::ptr::null_mut()) };
    }
}
